version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: liga
      RABBITMQ_DEFAULT_PASS: liga

  liga-db:
    image: postgres:14-alpine
    container_name: liga-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=liga
      - POSTGRES_USER=liga
      - POSTGRES_PASSWORD=liga

  delivery-service:
    build: delivery-service
    ports:
      - "8081:8081"
    depends_on:
      - liga-db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/liga
      - SPRING_DATASOURCE_USER=liga
      - SPRING_DATASOURCE_PASSWORD=liga

  kitchen-service:
    build: kitchen-service
    ports:
      - "8083:8083"
    depends_on:
      - liga-db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/liga
      - SPRING_DATASOURCE_USER=liga
      - SPRING_DATASOURCE_PASSWORD=liga

  notification-service:
    build: notification-service
    ports:
      - "8084:8084"
    depends_on:
      - liga-db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/liga
      - SPRING_DATASOURCE_USER=liga
      - SPRING_DATASOURCE_PASSWORD=liga

  order-service:
    build: order-service
    ports:
      - "8082:8082"
    depends_on:
      - liga-db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/liga
      - SPRING_DATASOURCE_USER=liga
      - SPRING_DATASOURCE_PASSWORD=liga

volumes:
  rabbitmq_data: