version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: liga
      RABBITMQ_DEFAULT_PASS: liga

  liga-db:
    image: postgres:14-alpine
    container_name: liga-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=liga
      - POSTGRES_USER=liga
      - POSTGRES_PASSWORD=liga
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liga"]
      interval: 10s
      timeout: 5s
      retries: 3

  liquibase:
    image: liquibase/liquibase:4.19.1
    container_name: liquibase
    depends_on:
      liga-db:
        condition: service_healthy
    environment:
      - LIQUIBASE_CHANGELOG=./migration/src/main/resources/db/master.xml
      - LIQUIBASE_URL=jdbc:postgresql://liga-db:5432/liga
      - LIQUIBASE_USERNAME=liga
      - LIQUIBASE_PASSWORD=liga
    command: --LIQUIBASE_CHANGELOG update

  delivery-service:
    build: delivery-service
    container_name: delivery-service
    ports:
      - "8081:8081"
    depends_on:
      - liga-db
      - liquibase
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/liga
      - SPRING_DATASOURCE_USER=liga
      - SPRING_DATASOURCE_PASSWORD=liga

  kitchen-service:
    build: kitchen-service
    container_name: kitchen-service
    ports:
      - "8083:8083"
    depends_on:
      - liga-db
      - liquibase
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/liga
      - SPRING_DATASOURCE_USER=liga
      - SPRING_DATASOURCE_PASSWORD=liga

  notification-service:
    build: notification-service
    container_name: notification-service
    ports:
      - "8084:8084"
    depends_on:
      - liga-db
      - liquibase
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/liga
      - SPRING_DATASOURCE_USER=liga
      - SPRING_DATASOURCE_PASSWORD=liga

  order-service:
    build: order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - liga-db
      - liquibase
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/liga
      - SPRING_DATASOURCE_USER=liga
      - SPRING_DATASOURCE_PASSWORD=liga