server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://127.0.0.1:8082/orders
          predicates:
            - Path=/orders/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: kitchen-service
          uri: http://127.0.0.1:8083/kitchen
          predicates:
            - Path=/kitchen/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: delivery-service
          uri: http://127.0.0.1:8081/deliveries
          predicates:
            - Path=/deliveries/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid,message.read
        provider:
          spring:
            issuer-uri: http://localhost:9000

springdoc:
  swagger-ui:
    urls:
      - name: Order Service API
        url: /orders/v3/api-docs
      - name: Delivery Service API
        url: /deliveries/v3/api-docs
      - name: Kitchen Service API
        url: /kitchen/v3/api-docs
